source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MyTextField_Example', :exclusive => true do
  pod 'MyTextField', :path => '../'
end

target 'MyTextField_Tests', :exclusive => true do
  pod 'MyTextField', :path => '../'

  
end
